### ISSUE TITLE
test6.ref

### ISSUE THREAD

**Issue by florinrm** [rosedu/problema-cdl-2019#1]
La liniile 37-41 (si 91-95) avem in felul urmator:

adjustment-adjustment-adjustment : 1 2 3 
adjustment-adjustment-afternoon : 1 2 3 
adjustment-adjustment-afternoon : 1 2 3 
adjustment-adjustment-bow : 1 2 3 
adjustment-adjustment-egg : 1 2 3 

Aici avem 2 cuvinte identice, adjustment-adjustment-afternoon, care ar trebui sa apara doar o data. Eu am urmatorul output, la aceleasi linii :

adjustment-adjustment-adjustment : 1 2 3 
adjustment-adjustment-afternoon : 1 2 3 
adjustment-adjustment-bow : 1 2 3 
adjustment-adjustment-egg : 1 2 3 
adjustment-adjustment-feigned : 1 2 3 

In rest am identic, aici este output-ul meu [1].

[1] https://pastebin.com/mTkxDcDG

**Comment by Andu033** [comment]
Si mie imi da exact la fel . Si eu cred ca testul e gresit.

**Comment by AnaDenisa** [comment]
Da, si eu am aceeasi problema.

**Comment by epureionut99** [comment]
Da, am corectat acum testul. Ne cerem scuze pentru eroare.
